-- MySQL Script generated by MySQL Workbench
-- Sat Nov 23 19:35:47 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

USE HospitalManagementDB;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema HospitalManagementDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `table1` ;

CREATE TABLE IF NOT EXISTS `table1` (
  `idtable1` INT NOT NULL,
  PRIMARY KEY (`idtable1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Patient` ;

CREATE TABLE IF NOT EXISTS `Patient` (
  `patient_id` INT NOT NULL,
  `account_id` INT NULL,
  PRIMARY KEY (`patient_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Certifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Certifications` ;

CREATE TABLE IF NOT EXISTS `Certifications` (
  `certs_id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`certs_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Account` ;

CREATE TABLE IF NOT EXISTS `Account` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `patient_id` INT NULL,
  `creation_date` DATE NULL,
  PRIMARY KEY (`account_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Emergency Contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Emergency Contact` ;

CREATE TABLE IF NOT EXISTS `Emergency Contact` (
  `emergency_contact_id` INT NOT NULL AUTO_INCREMENT,
  `patient_id` INT NOT NULL,
  `phone_number` INT NULL,
  `relationship` VARCHAR(45) NULL,
  `full_name` VARCHAR(45) NULL,
  PRIMARY KEY (`emergency_contact_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Specialization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Specialization` ;

CREATE TABLE IF NOT EXISTS `Specialization` (
  `specialization_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`specialization_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Doctor` ;

CREATE TABLE IF NOT EXISTS `Doctor` (
  `doctor_id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(45) NULL,
  `first_name` VARCHAR(45) NULL,
  `specialization_id` INT NOT NULL,
  PRIMARY KEY (`doctor_id`),
  UNIQUE INDEX `specialization_id_UNIQUE` (`specialization_id` ASC) VISIBLE,
  CONSTRAINT `specialization_id`
    FOREIGN KEY (`specialization_id`)
    REFERENCES `Specialization` (`specialization_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Nurse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Nurse` ;

CREATE TABLE IF NOT EXISTS `Nurse` (
  `nurse_id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `certs_id` INT NULL,
  PRIMARY KEY (`nurse_id`),
  UNIQUE INDEX `certs_id_UNIQUE` (`certs_id` ASC) VISIBLE,
  CONSTRAINT `certs_id`
    FOREIGN KEY (`certs_id`)
    REFERENCES `Certifications` (`certs_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Patient` ;

CREATE TABLE IF NOT EXISTS `Patient` (
  `patient_id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `DOB` DATE NULL,
  `emergency_contact_id` INT NULL,
  `medical_record_id` INT NULL,
  `doctor_id` INT NULL,
  `nurse_id` INT NOT NULL,
  `age` INT NULL,
  `full_name` VARCHAR(45) NULL,
  PRIMARY KEY (`patient_id`, `account_id`),
  INDEX `account_id_idx` (`account_id` ASC) VISIBLE,
  INDEX `doctor_id_idx` (`doctor_id` ASC) VISIBLE,
  INDEX `emergency_contact_id_idx` (`emergency_contact_id` ASC) VISIBLE,
  INDEX `nurse_id_idx` (`nurse_id` ASC) VISIBLE,
  CONSTRAINT `account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `emergency_contact_id`
    FOREIGN KEY (`emergency_contact_id`)
    REFERENCES `Emergency Contact` (`emergency_contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `doctor_id`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `Doctor` (`doctor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `nurse_id`
    FOREIGN KEY (`nurse_id`)
    REFERENCES `Nurse` (`nurse_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Allergies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Allergies` ;

CREATE TABLE IF NOT EXISTS `Allergies` (
  `patient_id` INT NOT NULL,
  `severity` VARCHAR(45) NULL,
  `allergen` VARCHAR(45) NULL,
  PRIMARY KEY (`patient_id`),
  CONSTRAINT `patient_id`
    FOREIGN KEY (`patient_id`)
    REFERENCES `Patient` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Payment` ;

CREATE TABLE IF NOT EXISTS `Payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) NULL,
  `card_number` INT NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`payment_id`),
  CONSTRAINT `fk_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Medication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Medication` ;

CREATE TABLE IF NOT EXISTS `Medication` (
  `medication_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `instructions` VARCHAR(45) NULL,
  PRIMARY KEY (`medication_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prescription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Prescription` ;

CREATE TABLE IF NOT EXISTS `Prescription` (
  `presc_id` INT NOT NULL,
  `doctor_id` INT NOT NULL,
  `medication_id` INT NOT NULL,
  `patient_id` INT NOT NULL,
  `dosage` VARCHAR(45) NULL,
  PRIMARY KEY (`presc_id`, `doctor_id`, `patient_id`, `medication_id`),
  INDEX `doctor_id_idx` (`doctor_id` ASC) VISIBLE,
  UNIQUE INDEX `doctor_id_UNIQUE` (`doctor_id` ASC) VISIBLE,
  UNIQUE INDEX `medication_id_UNIQUE` (`medication_id` ASC) VISIBLE,
  UNIQUE INDEX `patient_id_UNIQUE` (`patient_id` ASC) VISIBLE,
  CONSTRAINT `fk_doctor_id`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `Doctor` (`doctor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_id`
    FOREIGN KEY (`patient_id`)
    REFERENCES `Patient` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medication_id`
    FOREIGN KEY (`medication_id`)
    REFERENCES `Medication` (`medication_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Diagnosis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Diagnosis` ;

CREATE TABLE IF NOT EXISTS `Diagnosis` (
  `diagnosis_id` INT NOT NULL,
  `patient_id` INT NULL,
  `doctor_id` INT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`diagnosis_id`),
  INDEX `patient_id_idx` (`patient_id` ASC) VISIBLE,
  INDEX `doctor_id_idx` (`doctor_id` ASC) VISIBLE,
  CONSTRAINT `fk_diagnosis_patient_id`
    FOREIGN KEY (`patient_id`)
    REFERENCES `Patient` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diagnosis_doctor_id`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `Doctor` (`doctor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Department` ;

CREATE TABLE IF NOT EXISTS `Department` (
  `dept_id` INT NOT NULL,
  `phone_number` INT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`dept_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rooms` ;

CREATE TABLE IF NOT EXISTS `Rooms` (
  `room_id` INT NOT NULL,
  `nurse_id` INT NULL,
  `number` INT NULL,
  `dept_id` INT NULL,
  PRIMARY KEY (`room_id`),
  INDEX `nurse_id_idx` (`nurse_id` ASC) VISIBLE,
  INDEX `dept_id_idx` (`dept_id` ASC) VISIBLE,
  CONSTRAINT `fk_nurse_id`
    FOREIGN KEY (`nurse_id`)
    REFERENCES `Nurse` (`nurse_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dept_id`
    FOREIGN KEY (`dept_id`)
    REFERENCES `Department` (`dept_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Appointments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Appointments` ;

CREATE TABLE IF NOT EXISTS `Appointments` (
  `appt_id` INT NOT NULL,
  `patient_id` INT NULL,
  `doctor_id` INT NULL,
  `reason_for_visit` VARCHAR(45) NULL,
  `date_time` VARCHAR(45) NULL,
  PRIMARY KEY (`appt_id`),
  CONSTRAINT `fk_appointments_patient_id`  
    FOREIGN KEY (`patient_id`)  
    REFERENCES `Patient` (`patient_id`)  
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointments_doctor_id`
    FOREIGN KEY (`doctor_id`) 
    REFERENCES `Doctor` (`doctor_id`)  
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bill` ;

CREATE TABLE IF NOT EXISTS `Bill` (
  `bill_id` INT NOT NULL,
  `appt_id` INT NOT NULL,
  `payment_id` INT NOT NULL,
  `due_date` DATE NULL,
  PRIMARY KEY (`bill_id`, `payment_id`, `appt_id`),
  INDEX `appt_id_idx` (`appt_id` ASC) VISIBLE,
  INDEX `payment_id_idx` (`payment_id` ASC) VISIBLE,
  CONSTRAINT `appt_id`
    FOREIGN KEY (`appt_id`)
    REFERENCES `Appointments` (`appt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `payment_id`
    FOREIGN KEY (`payment_id`)
    REFERENCES `Payment` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lab Test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lab Test` ;

CREATE TABLE IF NOT EXISTS `Lab Test` (
  `patient_id` INT NOT NULL,
  `doctor_id` INT NULL,
  `result` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  INDEX `patient_id_idx` (`patient_id` ASC) VISIBLE,
  INDEX `doctor_id_idx` (`doctor_id` ASC) VISIBLE,
  CONSTRAINT `fk_labtest_patient_id`
    FOREIGN KEY (`patient_id`)
    REFERENCES `Patient` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_labtest_doctor_id`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `Doctor` (`doctor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Medical Records`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Medical Records` ;

CREATE TABLE IF NOT EXISTS `Medical Records` (
  `patient_id` INT NOT NULL,
  `doctor_id` INT NULL,
  `date` DATE NULL,
  INDEX `patient_id_idx` (`patient_id` ASC) VISIBLE,
  INDEX `doctor_id_idx` (`doctor_id` ASC) VISIBLE,
  CONSTRAINT `fk_medicalrecords_patient_id`
    FOREIGN KEY (`patient_id`)
    REFERENCES `Patient` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicalrecords_doctor_id`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `Doctor` (`doctor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Parent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Parent` ;

CREATE TABLE IF NOT EXISTS `Parent` (
  `parent_id` INT NOT NULL,
  `occupation` VARCHAR(45) NULL,
  `relationship_to_child` VARCHAR(45) NULL,
  `patient_id` INT NOT NULL,
  PRIMARY KEY (`parent_id`),
  UNIQUE INDEX `patient_id_UNIQUE` (`patient_id` ASC) VISIBLE,
  CONSTRAINT `fk_parent_patient_id`
    FOREIGN KEY (`patient_id`)
    REFERENCES `Patient` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Child`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Child` ;

CREATE TABLE IF NOT EXISTS `Child` (
  `patient_id` INT NOT NULL,
  `grade_level` INT NULL,
  `parent_id` INT NOT NULL,
  CONSTRAINT `fk_child_patient_id`
    FOREIGN KEY (`patient_id`)
    REFERENCES `Patient` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_child_parent_id`
    FOREIGN KEY (`parent_id`)
    REFERENCES `Parent` (`parent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
